name: Spring Boot App CI/CD with EBS
run-name: Testing and Deploying Spring Boot App to AWS EBS
on:
  push:
    branches: [ "main" ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn -B test
