name: Spring Boot App CI/CD with EBS
run-name: Testing and Deploying Spring Boot App to AWS EBS
on:
  push:
    branches: [ "main" ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      CICD_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      CICD_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      CICD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SERVER_PORT: 5000
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn -B test

  build:
    needs: tests #establecer dependencia de tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build project (.jar)
        run: mvn -B package -DskipTests --file pom.xml #compilar y omitir tests porque ya se ejecutaron
      - name: Upload .jar
        uses: actions/upload-artifact@v4.1.0 #guardar el archivo compilado para poder enviarlo a AWS
        with:
          name: artifact
          path: target/cicd-0.0.1-SNAPSHOT.jar #Path donde se desea guardar el archivo
